export const DOWNLOADING = "DOWNLOADING";

export const DOWNLOADING_SUCCESS = "DOWNLOADING_SUCCESS";
export const DOWNLOADING_ERROR = "DOWNLOADING_ERROR";

// export const SELECT_ITEM = "SELECT_ITEM";
